/**
 * Department-Based Officer Routing & Issue Classification Utility
 * Parul University Campus Maintenance Management System
 */

export const DEPARTMENTS = [
  'ELECTRICAL_ISSUES',
  'PLUMBING_WATER_ISSUES',
  'INFRASTRUCTURE_FURNITURE_ISSUES',
  'WASHROOM_ISSUES',
  'IT_NETWORK_ISSUES',
  'CLEANLINESS_WASTE_ISSUES',
  'SAFETY_SECURITY_ISSUES',
  'LIFT_MECHANICAL_ISSUES',
  'OUTDOOR_CAMPUS_ISSUES',
  'OTHER_MAINTENANCE_ISSUES'
]

export const DEPARTMENT_LABELS = {
  ELECTRICAL_ISSUES: 'Electrical Issues',
  PLUMBING_WATER_ISSUES: 'Plumbing & Water Issues',
  INFRASTRUCTURE_FURNITURE_ISSUES: 'Infrastructure & Furniture Issues',
  WASHROOM_ISSUES: 'Washroom Issues',
  IT_NETWORK_ISSUES: 'IT & Network Issues',
  CLEANLINESS_WASTE_ISSUES: 'Cleanliness & Waste Issues',
  SAFETY_SECURITY_ISSUES: 'Safety & Security Issues',
  LIFT_MECHANICAL_ISSUES: 'Lift & Mechanical Issues',
  OUTDOOR_CAMPUS_ISSUES: 'Outdoor & Campus Issues',
  OTHER_MAINTENANCE_ISSUES: 'Other Maintenance Issues'
}

/**
 * Deterministic mapping table from fine-grained issueType / legacy damageType
 * to authoritative department enum value.
 */
export const ISSUE_TYPE_TO_DEPARTMENT = {
  // Electrical
  FAN_NOT_WORKING: 'ELECTRICAL_ISSUES',
  LIGHT_NOT_WORKING: 'ELECTRICAL_ISSUES',
  AC_NOT_WORKING: 'ELECTRICAL_ISSUES',
  SWITCH_DAMAGED: 'ELECTRICAL_ISSUES',
  SOCKET_DAMAGED: 'ELECTRICAL_ISSUES',
  WIRING_ISSUE: 'ELECTRICAL_ISSUES',
  FAN: 'ELECTRICAL_ISSUES',
  LIGHT: 'ELECTRICAL_ISSUES',
  AC: 'ELECTRICAL_ISSUES',
  PLUG_SOCKET: 'ELECTRICAL_ISSUES',
  ELECTRICAL: 'ELECTRICAL_ISSUES',

  // Plumbing & Water
  WATER_LEAKAGE: 'PLUMBING_WATER_ISSUES',
  TAP_DAMAGED: 'PLUMBING_WATER_ISSUES',
  PIPE_LEAKAGE: 'PLUMBING_WATER_ISSUES',
  DRAIN_BLOCKAGE: 'PLUMBING_WATER_ISSUES',
  FLUSH_PROBLEM: 'PLUMBING_WATER_ISSUES',
  WATER_SUPPLY_ISSUE: 'PLUMBING_WATER_ISSUES',
  WATER_LEAK: 'PLUMBING_WATER_ISSUES',
  PLUMBING: 'PLUMBING_WATER_ISSUES',

  // Infrastructure & Furniture
  CHAIR_DAMAGED: 'INFRASTRUCTURE_FURNITURE_ISSUES',
  TABLE_DAMAGED: 'INFRASTRUCTURE_FURNITURE_ISSUES',
  CUPBOARD_DAMAGED: 'INFRASTRUCTURE_FURNITURE_ISSUES',
  DOOR_DAMAGED: 'INFRASTRUCTURE_FURNITURE_ISSUES',
  DOOR_LOCK_DAMAGED: 'INFRASTRUCTURE_FURNITURE_ISSUES',
  SHELF_DAMAGED: 'INFRASTRUCTURE_FURNITURE_ISSUES',
  WINDOW_DAMAGED: 'INFRASTRUCTURE_FURNITURE_ISSUES',
  WALL_DAMAGE: 'INFRASTRUCTURE_FURNITURE_ISSUES',
  FLOOR_DAMAGE: 'INFRASTRUCTURE_FURNITURE_ISSUES',
  CEILING_DAMAGE: 'INFRASTRUCTURE_FURNITURE_ISSUES',
  BENCH: 'INFRASTRUCTURE_FURNITURE_ISSUES',
  CHAIR: 'INFRASTRUCTURE_FURNITURE_ISSUES',
  DESK: 'INFRASTRUCTURE_FURNITURE_ISSUES',
  DOOR: 'INFRASTRUCTURE_FURNITURE_ISSUES',
  WINDOW: 'INFRASTRUCTURE_FURNITURE_ISSUES',
  CLASSROOM_EQUIPMENT: 'INFRASTRUCTURE_FURNITURE_ISSUES',

  // Washroom
  WASHROOM_CLEANLINESS: 'WASHROOM_ISSUES',
  TOILET_DAMAGE: 'WASHROOM_ISSUES',
  WASH_BASIN_PROBLEM: 'WASHROOM_ISSUES',
  WASHROOM_LEAKAGE: 'WASHROOM_ISSUES',
  WASHROOM: 'WASHROOM_ISSUES',

  // IT & Network
  WIFI_NOT_WORKING: 'IT_NETWORK_ISSUES',
  NETWORK_ISSUE: 'IT_NETWORK_ISSUES',
  LAN_ISSUE: 'IT_NETWORK_ISSUES',
  COMPUTER_NOT_WORKING: 'IT_NETWORK_ISSUES',
  PROJECTOR_NOT_WORKING: 'IT_NETWORK_ISSUES',
  CCTV_NOT_WORKING: 'IT_NETWORK_ISSUES',
  PROJECTOR: 'IT_NETWORK_ISSUES',
  WIFI_NETWORK: 'IT_NETWORK_ISSUES',
  LAB_EQUIPMENT: 'IT_NETWORK_ISSUES',

  // Cleanliness & Waste
  GARBAGE_OVERFLOW: 'CLEANLINESS_WASTE_ISSUES',
  CLEANING_REQUIRED: 'CLEANLINESS_WASTE_ISSUES',
  WASTE_DISPOSAL: 'CLEANLINESS_WASTE_ISSUES',
  PEST_ISSUE: 'CLEANLINESS_WASTE_ISSUES',
  CLEANLINESS: 'CLEANLINESS_WASTE_ISSUES',
  GARBAGE: 'CLEANLINESS_WASTE_ISSUES',

  // Safety & Security
  BROKEN_RAILING: 'SAFETY_SECURITY_ISSUES',
  FIRE_SAFETY_ISSUE: 'SAFETY_SECURITY_ISSUES',
  EMERGENCY_EXIT_ISSUE: 'SAFETY_SECURITY_ISSUES',
  DANGEROUS_WIRING: 'SAFETY_SECURITY_ISSUES',
  SECURITY_ISSUE: 'SAFETY_SECURITY_ISSUES',

  // Lift & Mechanical
  LIFT_NOT_WORKING: 'LIFT_MECHANICAL_ISSUES',
  LIFT_DOOR_ISSUE: 'LIFT_MECHANICAL_ISSUES',
  GENERATOR_ISSUE: 'LIFT_MECHANICAL_ISSUES',
  WATER_PUMP_ISSUE: 'LIFT_MECHANICAL_ISSUES',
  MOTOR_ISSUE: 'LIFT_MECHANICAL_ISSUES',

  // Outdoor & Campus
  ROAD_DAMAGE: 'OUTDOOR_CAMPUS_ISSUES',
  PARKING_ISSUE: 'OUTDOOR_CAMPUS_ISSUES',
  STREET_LIGHT_ISSUE: 'OUTDOOR_CAMPUS_ISSUES',
  DRAINAGE_ISSUE: 'OUTDOOR_CAMPUS_ISSUES',
  GARDEN_ISSUE: 'OUTDOOR_CAMPUS_ISSUES',
  CAMPUS_SIGNBOARD_DAMAGE: 'OUTDOOR_CAMPUS_ISSUES',
  POTHOLE: 'OUTDOOR_CAMPUS_ISSUES',
  ROAD_CRACK: 'OUTDOOR_CAMPUS_ISSUES',
  STREETLIGHT: 'OUTDOOR_CAMPUS_ISSUES',
  SPORTS_FACILITY: 'OUTDOOR_CAMPUS_ISSUES',

  // Other
  OTHER_MAINTENANCE: 'OTHER_MAINTENANCE_ISSUES',
  HOSTEL_ISSUE: 'OTHER_MAINTENANCE_ISSUES',
  CANTEEN_ISSUE: 'OTHER_MAINTENANCE_ISSUES',
  LIBRARY_ISSUE: 'OTHER_MAINTENANCE_ISSUES',
  OTHER: 'OTHER_MAINTENANCE_ISSUES'
}

/**
 * Authoritative backend function to resolve department for a given issueType and AI department hint.
 * Prioritizes deterministic backend issueType mapping over AI department.
 * Ensures output is strictly within the 10 exact departments whitelist.
 */
export function getDepartmentForIssue (issueType = '', aiDepartment = '') {
  const normIssueType = String(issueType || '').trim().toUpperCase()
  const normAiDept = String(aiDepartment || '').trim().toUpperCase()

  // 1. Direct deterministic mapping from issueType
  if (normIssueType && ISSUE_TYPE_TO_DEPARTMENT[normIssueType]) {
    return ISSUE_TYPE_TO_DEPARTMENT[normIssueType]
  }

  // 2. Validate AI suggested department against whitelist
  if (normAiDept && DEPARTMENTS.includes(normAiDept)) {
    return normAiDept
  }

  // 3. Fallback for unmapped or unknown types
  return 'OTHER_MAINTENANCE_ISSUES'
}

/**
 * Normalization helpers for building and department comparison.
 * Trims leading/trailing whitespace and converts to lower-case.
 * Exact string equality (===) ONLY after trim + lowercase.
 */
export const normalizeBuilding = (value) => String(value || '').trim().toLowerCase()
export const normalizeDepartment = (value) => String(value || '').trim().toLowerCase()

